version: '2'

services:
  autoforward:
    image: alpine/socat
    restart: never
#    ports:
#      - "9998:8080"
    expose:
       - 8080
    environment:
      VIRTUAL_HOST: ${XIP_PREFIX}.161.106.174.22.xip.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${XIP_PREFIX}.161.106.174.22.xip.io
      LETSENCRYPT_EMAIL: raphael.bernhard@orange.com
    command: tcp-listen:8080,fork,reuseaddr tcp-connect:${TARGET_HOST}:${TARGET_PORT}
    networks:
      - auto_https_reverse_proxy

networks:
  auto_https_reverse_proxy:
    external:
      name: webservices

